[atom]
id = "pkdjz"
version = "0.1.0"
system = true
propagate = true

[features]
default = ["lib", "pkgs"]

[backend.nix]
fetcher = "flake-lock"

[fetch.lib]
name = "nixpkgs-lib"
type = "import"
subdir = "lib"

[fetch.pkgs]
name = "nixpkgs"
type = "pkgs"

[fetch.omnix]
name = "omnix"
type = "flake"

[fetch.zed]
name = "zed"
type = "flake"

[fetch.hugo-themes-srcs]
name = "self"
type = "import"
subdir = "hugo-themes-srcs"